import Navbar from "@/components/layout/Navbar";
import "../../styles/main.scss";
import NextThemesProvider from "./provider";
import Footer from "@/components/layout/Footer";

export const metadata = {
  title: "Martine | Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <NextThemesProvider>
          <Navbar />
          <main>{children}</main>
          <Footer />
        </NextThemesProvider>
      </body>
    </html>
  );
}
